CREATE TABLE IF NOT EXISTS interaction_attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interaction_id BIGINT NOT NULL REFERENCES interactions(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  file_type TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE interaction_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own attachments" ON interaction_attachments
  FOR ALL USING (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS copilot_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL DEFAULT 'New Chat',
  messages_json TEXT NOT NULL DEFAULT '[]',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE copilot_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own copilot conversations" ON copilot_conversations
  FOR ALL USING (auth.uid() = user_id);
